# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'app5' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for app5

  pod 'Firebase/Core'
  pod 'Firebase/Auth'


  pod 'react-native-youtube', :path => '../node_modules/react-native-youtube'

  target 'app5Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'app5-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for app5-tvOS

  target 'app5-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
